### PR TITLE
EZP-29816: Make priority column in children list more prominent

### PR DESCRIPTION
**Pull request by tischsoic**
JIRA: https://jira.ez.no/browse/EZP-29816

When field is **not** active, arrows should appear only on hover. When field is active arrows should be visible all the time.
gkVxnObg7k

before             |  after
:-------------------------:|:-------------------------:
Screen Shot 2019-09-25 at 14 55 24  |  Screen Shot 2019-09-25 at 14 56 16
Screen Shot 2019-09-25 at 14 54 39  |  Screen Shot 2019-09-25 at 14 54 17

### CODE REVIEW

**Review by dew326 — APPROVED** [review]

**Review by inakijv — APPROVED** [review]

**Review by katarzynazawada — CHANGES_REQUESTED** [review]
On Firefox and Edge input box does not look like in the prototype 

Firefox:
Screenshot 2019-09-26 at 11 20 30
Edge:
Screenshot 2019-09-26 at 11 20 15

**Comment by katarzynazawada** [comment]
Now, priority column is grayed out on Firefox 
Screenshot 2019-09-26 at 13 42 46

**Comment by crevillo** [comment]
looks good to me. thanks for taking care of this.

**Review by katarzynazawada — APPROVED** [review]

**Comment by lserwatka** [comment]
You can merge it up.

**Comment by tischsoic** [comment]
Merged up:
- master: https://github.com/ezsystems/ezplatform-admin-ui-modules/commit/745b4e217c7ee688ca6afbee038bf64800be5e3a

**Pull request merged**
