### PR TITLE
EZP-29155: Priority buttons work in the same way

### PR DESCRIPTION
**Pull request by ViniTou**
| Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZP-29155
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no

### CODE REVIEW

**Review by dew326 — CHANGES_REQUESTED** [review]
This is not a valid solution.
We have a bug but somewhere else. `onChange` we take the value from input value (which is static as React doesn't update those values). 
So for the fix, you have to change in this line:
https://github.com/ezsystems/ezplatform-admin-ui-modules/blob/master/src/modules/sub-items/components/table-view/table.view.item.component.js#L81
`this._refPriorityInput.value` into `event.target.value`

**Comment by lserwatka** [comment]
@ViniTou do you have any progress on this one?

**Comment by ViniTou** [comment]
@lserwatka 
We were discussing this internally on slack, solution provided by @dew326 doesn't work, and as was decided with @sunpietro this solution is acceptable in this case.

**Review by dew326 — APPROVED** [review]

**Comment by lserwatka** [comment]
Great, let's keep the ball rolling

**Review by barbaragr — APPROVED** [review]

**Pull request merged**
