### PR TITLE
EZP-30128: Bulk delete - User account partially deleted

### PR DESCRIPTION
**Pull request by tischsoic**
JIRA: https://jira.ez.no/browse/EZP-30128

### CODE REVIEW

**Review by dew326 — APPROVED** [review]

**Comment by tischsoic** [comment]
Can you please check translations, @SylvainGuittard ?

**Review by m-tyrala — APPROVED** [review]
QA approves

**Comment by lserwatka** [comment]
@tischsoic you can merge it up.

**Comment by tischsoic** [comment]
merged up: 
- master: https://github.com/ezsystems/ezplatform-admin-ui-modules/commit/fb49aff78f0a1a54b1ebdc834dda387620abaed4

**Pull request merged**
