### PR TITLE
EZP-30341: Needless scroll in UDW

### PR DESCRIPTION
**Pull request by tischsoic**
JIRA: https://jira.ez.no/browse/EZP-30341

### CODE REVIEW

**Comment by tischsoic** [comment]
This PR fixes also this double scroll:
Screen Shot 2019-03-28 at 10 55 23

I tested solution on Chrome, Firefox and Safari.

**Comment by tischsoic** [comment]
### For QA
Please check every tab from UDW with different widths/heights of browser window on different browsers to assure that everything is working correctly. 🙂

**Review by dew326 — APPROVED** [review]

**Review by barbaragr — APPROVED** [review]

**Comment by lserwatka** [comment]
Could you merge it up?

**Comment by tischsoic** [comment]
Merged up:
- master: https://github.com/ezsystems/ezplatform-admin-ui-modules/commit/5c2250d0d1b1b9e38be19d4b9ad5348cd793a598

**Pull request merged**
