### PR TITLE
EZP-29424: I want Confirmed items in UDW to be differentiated from the background

### PR DESCRIPTION
**Pull request by tischsoic**
After changes background of Confirmed items should be darker.
This PR reverts one change from previous PR.

JiRA: https://jira.ez.no/browse/EZP-29424

Before:
screen shot 2018-07-17 at 08 50 40

After:
screen shot 2018-07-17 at 08 56 35

### CODE REVIEW

**Review by dew326 — APPROVED** [review]

**Comment by lserwatka** [comment]
@tischsoic could you change it to 1.2 branch?

**Comment by tischsoic** [comment]
@lserwatka I changed base branch to 1.2.

**Review by sunpietro — CHANGES_REQUESTED** [review]
The overall look doesn't look good. It needs improvements.
It has to be consulted with @inakijv

**Comment by lserwatka** [comment]
@sunpietro this feature and desing was there before 2.2 release and it was already consulted. Somone messed up this CSS so it did not go to release.

**Comment by lserwatka** [comment]
@tischsoic you can merge it up.

**Pull request merged**
