### PR TITLE
[WIP] EZP-29937: Content type names are not translated in the Create tab of UDW

### PR DESCRIPTION
**Pull request by sunpietro**
https://jira.ez.no/browse/EZP-29937

### CODE REVIEW

**Comment by sunpietro** [comment]
It will require some backend done by @alongosz

**Comment by dew326** [comment]
It seems like very complicated. Getting the preferred language, checking names in all languages, selecting the one from preferred.

In the AdminUiConfig we have the object with `contentType.identifier` and `contentType.name`, why this name cannot be translated by the backend? @alongosz

**Review by dew326 — CHANGES_REQUESTED** [review]
.

**Comment by sunpietro** [comment]
@dew326 I didn't want to mess up with property values as they are used in other contexts

**Comment by dew326** [comment]
Exactly, and all usage of this content type name should be translated.

**Comment by lserwatka** [comment]
@dew326 is right, we should reuse this, or add a new key to this array with translated names.

**Comment by dew326** [comment]
We do not need a new key. We want to all usage of `name` to be translated automatically.

**Comment by alongosz** [comment]
Sorry I didn't see this specific config before. Indeed that seems like the cleanest way. AdminUI PR will be posted in a few minutes. Change of `eZ.adminUiConfig.contentTypeNames` is already working for me there.

**Comment by sunpietro** [comment]
For displaying the content type items' names we're using `contentTypes` prop with the value of `window.eZ.adminUiConfig.contentTypes`. It's passed to the `UniversalDiscoveryModule` when initializing.

**Comment by dew326** [comment]
I think we should change this in both `eZ.adminUiConfig.contentTypeNames` and `eZ.adminUiConfig.contentTypes`.

**Comment by sunpietro** [comment]
Ok, looks like this PR is irrelevant as no changes are required on the frontend side. Right @dew326 and @alongosz ?

**Comment by alongosz** [comment]
Yes, it can be closed.

**Comment by andrerom** [comment]
> I think we should change this in both eZ.adminUiConfig.contentTypeNames and eZ.adminUiConfig.contentTypes

@dew326 be aware these could be combined to one to avoid loading all content types twice on every request

**Comment by dew326** [comment]
@andrerom Yes, I know. We keep it in two because of the BC.

**Comment by andrerom** [comment]
@dew326 well we could find a way to set both js params based on same source data to avoid the extra load, or?

**Comment by sunpietro** [comment]
@andrerom are you aware this PR is closed?

**Comment by andrerom** [comment]
@sunpietro Fully, just like to taunt you ;)

But ok, I'll move the discussion to Slack ;)

**Comment by dew326** [comment]
@andrerom probably, we have to ask backend guys as this config is set there.

**Pull request closed without merging**
