### PR TITLE
EZP-29622: Date is not changed on UDW

### PR DESCRIPTION
**Pull request by dew326**
**Jira ticket:** https://jira.ez.no/browse/EZP-29622

### CODE REVIEW

**Review by tischsoic — APPROVED** [review]

**Review by sunpietro — APPROVED** [review]
As soon as we get a response from MomentJS maintainers we can improve it later.

**Comment by micszo** [comment]
There's an issue with 2 hours shift between Versions tab and UDW. 🙂

**Comment by dew326** [comment]
ping @micszo  
PR requires: https://github.com/ezsystems/ezplatform-admin-ui/pull/665

**Comment by micszo** [comment]
~Does it take Archived instead of Published? Is this correct?~ Wait, I think it makes sense. 🙂 
screen shot 2018-10-03 at 16 08 01
screen shot 2018-10-03 at 16 07 46

**Comment by dew326** [comment]
@micszo No, it takes the same time as previously `publishedDate` https://github.com/ezsystems/ezplatform-admin-ui-modules/pull/105/files#diff-8e79a2b2c6cc298599a2bc39c981e81cR197

**Review by micszo — APPROVED** [review]

**Pull request merged**
