### PR TITLE
EZP-29701: Select content button's outline is cut at the bottom

### PR DESCRIPTION
**Pull request by tischsoic**
JIRA: https://jira.ez.no/browse/EZP-29701

Outline was remove as discussed with @inakijv

### CODE REVIEW

**Review by dew326 — APPROVED** [review]

**Review by sunpietro — APPROVED** [review]

**Comment by lserwatka** [comment]
@tischsoic shouldn't this go into 1.3 branch?

**Comment by lserwatka** [comment]
@tischsoic rebase is needed here.

**Comment by tischsoic** [comment]
@lserwatka @katarzynazawada rebased onto 1.3

**Review by katarzynazawada — APPROVED** [review]

**Comment by lserwatka** [comment]
You can merge it up.

**Comment by tischsoic** [comment]
Merged up to master: https://github.com/ezsystems/ezplatform-admin-ui-modules/commit/17de174da0d0df0928faaa6cf217c4eef9064f40

**Pull request merged**
