### PR TITLE
EZP-28437:  [UDW] Cannot select content when content selection limit is not set

### PR DESCRIPTION
**Pull request by sunpietro**
https://jira.ez.no/browse/EZP-28437

### CODE REVIEW

**Comment by micszo** [comment]
Aren't https://jira.ez.no/browse/EZP-28435 and https://jira.ez.no/browse/EZP-28437 duplicates? 🙂

**Review by barbaragr — APPROVED** [review]
Works fine.

**Review by dew326 — APPROVED** [review]

**Review by micszo — APPROVED** [review]
EE approved.

**Comment by lserwatka** [comment]
@micszo they are, you can close both. One was made by Sylvain last evening.

**Pull request merged**
