### PR TITLE
EZP-29872: Unnecessary duplication of the file size in multi-file upload

### PR DESCRIPTION
**Pull request by tischsoic**
JIRA: https://jira.ez.no/browse/EZP-29872

Removes duplicated `div`.

### CODE REVIEW

**Review by dew326 — APPROVED** [review]

**Review by sunpietro — APPROVED** [review]

**Review by katarzynazawada — APPROVED** [review]

**Comment by lserwatka** [comment]
rebase is needed

**Comment by tischsoic** [comment]
@lserwatka rebased

**Comment by lserwatka** [comment]
You can merge it up now

**Comment by tischsoic** [comment]
Merged up: https://github.com/ezsystems/ezplatform-admin-ui-modules/commit/2a941198da510633ab24cd2fe151b8ba7bd8c1b7

**Pull request merged**
