### PR TITLE
Coding standards fixes

### PR DESCRIPTION
**Pull request by sunpietro**
Coding standards fixes. Fixed using Prettier. That avoid commiting CS fixes in the future pull requests and it will help us focusing on real fixes.

- [x] fixed CS using Prettier,
- [x] Moved from `Object.assign` to object spread in Sub Items List,
- [x] Corrected binding context in the Sub Items List

### CODE REVIEW

**Review by dew326 — APPROVED** [review]

**Comment by tischsoic** [comment]
I hope it wont generate many conflicts with my branch on which I am changing translations in quite many files.

**Comment by tischsoic** [comment]
And I am calling Prettier in every file in which I am changing translations, so I think it would be good idea to wait with merging it after I finish translations.

**Comment by lserwatka** [comment]
@tischsoic yes, we won't rush with this one.

**Comment by sunpietro** [comment]
@tischsoic we can wait until you finish your work

**Comment by tischsoic** [comment]
We (@sunpietro & @dew326 and me) agreed in private that we can merge it and then solve conflicts.
@lserwatka

**Review by tischsoic — APPROVED** [review]

**Comment by lserwatka** [comment]
@sunpietro rebase is needed.

**Comment by sunpietro** [comment]
@lserwatka done

**Pull request merged**
