### PR TITLE
EZP-31045: Subitems warning about using checked prop without onChange handler

### PR DESCRIPTION
**Pull request by dew326**
**Jira ticket:** https://jira.ez.no/browse/EZP-31045

**Note:** This PR should be tested if still works: https://github.com/ezsystems/ezplatform-admin-ui-modules/pull/215

### CODE REVIEW

**Review by katarzynazawada — CHANGES_REQUESTED** [review]
Subitems do not throw warning but three-state header checkbox do not work properly. Steps to reproduce vary depending on the browser.

**Chrome and Firefox**
1. Select several checkboxes.
2. Click on checkbox from the header. 

Header checkbox is checked but the rest of checkboxes are not. When clicking again on header checkbox it changes state to unchecked but others don't. See, please http://g.recordit.co/bc7f24CHFc.gif

**Edge**
1. Select all items.
2. Uncheck one.
3. Click on checkbox from the header.  

Same behavior as above. See, please http://g.recordit.co/6RxwSeShsb.gif

**Comment by m-tyrala** [comment]
Together with [EZP-30376](https://jira.ez.no/browse/EZP-30376), to upload test reports to the server, every repository contains encrypted ssh key now. This key is encrypted per repo, so decryption doesn't work on forks and builds fails on it.

**Review by katarzynazawada — APPROVED** [review]
Header checkbox works fine 🙂

**Comment by lserwatka** [comment]
Could you merge it up?

**Pull request merged**
